name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
    ANSIBLE_VERSION: 8.1.6
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build_image:
        name: Build Docker image
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Check out repo
              uses: actions/checkout@v4
            
            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build Docker images
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                context: ansible/ubuntu2204/
                build-args: ANSIBLE_VERSION=${{ env.ANSIBLE_VERSION }}
                push: false
                tags: |
                  ghcr.io/rangersms/ansible:${{ env.ANSIBLE_VERSION }}-ubuntu2204